LastTest.Responsive/Controllers/AccountsController.cs
using LastTest.Domain.Models.InputModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting.Server;
using Microsoft.AspNetCore.Hosting.Server.Features;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Threading.Tasks;

namespace LastTest.Responsive.Controllers
{
    [Route("accounts")]
    [AllowAnonymous]
    public class AccountsController : Controller
    {
        public AccountsController
            (
                IServer server,
                UserManager<IdentityUser> userManager, SignInManager<IdentityUser> sessionManager)
        {
            _server = server;
            _userManager = userManager;
            _sessionManager = sessionManager;
        }

        readonly IServer _server;
        readonly UserManager<IdentityUser> _userManager;
        readonly SignInManager<IdentityUser> _sessionManager;

        [HttpGet]
        [Route("register")]
        public IActionResult Register()
        {
            RegisterInputModel model =
                new RegisterInputModel();

            return View(model);
        }

        [HttpPost]
        [Route("register")]
        public async Task<IActionResult> Register(RegisterInputModel model)
        {
            if (ModelState.IsValid)
            {
                var email = model.Email;

                var user =
                    new IdentityUser
                    {
                        UserName = email,
                        Email = email
                    };

                var result =
                    await _userManager.CreateAsync(user, password: model.Password);

                if (result.Succeeded)
                {
                    await _sessionManager.SignInAsync(user, isPersistent: false);
                    return RedirectToAction("index", "home");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            return View(model);
        }

        [HttpGet]
        [Route("login")]
        public async Task<IActionResult> Login()
        {
            LoginInputModel model =
                new LoginInputModel
                {
                    ExternalLogins =
                        (await _sessionManager.GetExternalAuthenticationSchemesAsync()).ToList()
                };

            return View(model);
        }

        [HttpPost]
        [Route("login")]
        public async Task<IActionResult> Login(LoginInputModel model)
        {
            if (ModelState.IsValid)
            {
                var result =
                    await _sessionManager.PasswordSignInAsync
                        (model.Email, model.Password, isPersistent: false, lockoutOnFailure: false);

                if (result.Succeeded)
                {
                    return RedirectToAction("index", "home");
                }

                ModelState.AddModelError(string.Empty, "Session could not be started!");
            }

            return View(model);
        }

        [HttpPost]
        [Route("logout")]
        public async Task<IActionResult> Logout()
        {
            await _sessionManager.SignOutAsync();
            return RedirectToAction("index", "home");
        }

        [HttpPost]
        [Route("externallogin")]
        //[AllowAnonymous]
        public IActionResult ExternalLogin(string provider, string returnUrl)
        {
            var redirectUrl =
                Url.Action
                    (action: "ExternalLoginCallback", new { ReturnUrl = returnUrl });

            var properties =
                _sessionManager.ConfigureExternalAuthenticationProperties
                    (provider, redirectUrl);

            return new ChallengeResult(provider, properties);
        }

        //[AllowAnonymous]
        public async Task<IActionResult> ExternalLoginCallback(string returnUrl = null, string remoteError = null)
        {
            if (string.IsNullOrEmpty(returnUrl))
                returnUrl = Url.Content("~/");

            LoginInputModel model =
                new LoginInputModel
                {
                    ReturnUrl = returnUrl,
                    ExternalLogins = (await _sessionManager.GetExternalAuthenticationSchemesAsync()).ToList()
                };

            if (!string.IsNullOrEmpty(remoteError))
            {
                ModelState.AddModelError(string.Empty, $"Provider has reported the following error: {remoteError}");
                return View(model);
            }

            var info =
                await _sessionManager.GetExternalLoginInfoAsync();

            var result =
                await _sessionManager.ExternalLoginSignInAsync
                    (info.LoginProvider, info.ProviderKey, isPersistent: false);

            if (result.Succeeded)
            {
                return LocalRedirect(returnUrl);
            }
            else
            {
                var email = info.Principal.FindFirst(ClaimTypes.Email).Value;

                if (!string.IsNullOrEmpty(email))
                {
                    var user = await _userManager.FindByEmailAsync(email);

                    if (user == null)
                    {
                        user =
                            new IdentityUser
                            {
                                Email = email,
                                UserName = email
                            };

                        await _userManager.CreateAsync(user);
                    }

                    await _userManager.AddLoginAsync(user, info);
                    await _sessionManager.SignInAsync(user, isPersistent: false);
                    return LocalRedirect(returnUrl);
                }
            }

            ModelState.AddModelError(string.Empty, $"{info.ProviderDisplayName} has not responded.");
            return View(model);
        }

        [Route("checkemail")]
        //[AllowAnonymous]
        public async Task<JsonResult> CheckEmail(string email)
        {
            var user =
                await _userManager.FindByEmailAsync(email);

            if (user == null)
            {
                return Json(true);
            }

            return Json($"Email {email} already exists!");
        }

        [Route("accessdenied")]
        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

LastTest.Responsive/Controllers/AdministrationController.cs
using LastTest.Application.Handlers;
using LastTest.Domain.Models.Entities;
using LastTest.Domain.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace LastTest.Responsive.Controllers
{
    [Route("[controller]")]
    public class AdministrationController : Controller
    {
        public AdministrationController
            (RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        readonly RoleManager<IdentityRole> _roleManager;
        readonly UserManager<IdentityUser> _userManager;
        //[Authorize(Policy = PermissionTypeNames.ADMINISTRADOR)]
        public IActionResult Index()
        {
            RoleViewModel model =
                new RoleViewModel
                {
                    Roles =
                        _roleManager.Roles.Select
                            (s => new Role { Id = s.Id, Name = s.Name })
                };

            return View(model);
        }

        [HttpGet]
        [Route("[action]")]
        [Route("[action]/{id}")]
        //[Authorize(Policy = PermissionTypeNames.ADMINISTRADOR)]
        public async Task<IActionResult> Upsert(string id = null)
        {
            Role role = new Role();

            if (!string.IsNullOrEmpty(id))
            {
                IdentityRole identityRole = await _roleManager.FindByIdAsync(id);

                if (identityRole == null)
                {
                    return NotFound();
                }

                role.Id = identityRole.Id;
                role.Name = identityRole.Name;
            }

            return View(role);
        }

        [HttpPost]
        [Route("[action]")]
        [Route("[action]/{id}")]
        //[Authorize(Policy = PermissionTypeNames.ADMINISTRADOR)]
        public async Task<IActionResult> Upsert(Role model, string id = null)
        {
            if (ModelState.IsValid)
            {
                IdentityRole role = new IdentityRole();

                if (!string.IsNullOrEmpty(model.Id))
                {
                    role = await _roleManager.FindByIdAsync(model.Id);
                }

                role.Name = model.Name;

                var result =
                    !string.IsNullOrEmpty(model.Id)
                        ? await _roleManager.UpdateAsync(role)
                        : await _roleManager.CreateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("index");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            return View(model);
        }

        [HttpGet]
        [Route("[action]/{id}")]
        //[Authorize(Policy = PermissionTypeNames.ADMINISTRADOR)]
        public async Task<IActionResult> UsersRole(string id)
        {
            UserRoleViewModel model = new UserRoleViewModel
            {
                Role = id
            };

            if (string.IsNullOrEmpty(id))
            {
                return BadRequest();
            }

            IdentityRole role = await _roleManager.FindByIdAsync(id);

            if (role == null)
            {
                return NotFound();
            }

            foreach (var user in _userManager.Users)
            {
                UserRole output =
                    new UserRole
                    {
                        Email = user.Email,
                        Selected =
                            await _userManager.IsInRoleAsync(user, role.Name)
                    };
                model.Users.Add(output);
            }

            return View(model);
        }

        [HttpGet]
        [Route("[action]")]
        //[Authorize(Policy = PermissionTypeNames.ADMINISTRADOR)]
        public async Task<IActionResult> getAllUsers()
        {
            UsersViewModel model = new();

            foreach (var user in _userManager.Users)
            {

                UsersAll output = new UsersAll
                {
                    Email = user.Email,
                    Role = await _userManager.GetRolesAsync(user)
                };

                model.UsersAll.Add(output);
            }
            return View(model);
        }

        [HttpPost]
        [Route("[action]/{id}")]
      //  [Authorize(Policy = PermissionTypeNames.ADMINISTRADOR)]
        public async Task<IActionResult> UsersRole(UserRoleViewModel model, string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return BadRequest();
            }

            IdentityRole role = await _roleManager.FindByIdAsync(id);

            if (role == null)
            {
                return NotFound();
            }

            foreach (var input in model.Users)
            {
                var user = await _userManager.FindByEmailAsync(input.Email);
                IdentityResult result = null;

                if (input.Selected && !await _userManager.IsInRoleAsync(user, role.Name))
                {
                    result = await _userManager.AddToRoleAsync(user, role.Name);
                }
                else if (!input.Selected && await _userManager.IsInRoleAsync(user, role.Name))
                {
                    result = await _userManager.RemoveFromRoleAsync(user, role.Name);
                }

                if (result != null && !result.Succeeded)
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }

            return View(model);
        }
    }
}

LastTest.Responsive/Controllers/CarController.cs
using LastTest.Application.Handlers;
using LastTest.DataAccess.Repository;
using LastTest.DataAccess.Repository.UnitOfWork;
using LastTest.Domain.Models.DataModels;
using LastTest.Domain.Models.InputModels;
using LastTest.Domain.Models.ViewModels;
using LastTest.Infrastructure.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace LastTest.Responsive.Controllers
{
    public class CarController : Controller
    {
        
        public CarController(IUnitOfWork<ApplicationDbContext> unitOfWork)
        {
            _unitOfWork = unitOfWork;
            _carRepository = _unitOfWork.Repository<Car>();
            _statusRepository = _unitOfWork.Repository<ReservationStatus>();

        }

        readonly IUnitOfWork<ApplicationDbContext> _unitOfWork;
        readonly IRepository<Car> _carRepository;
        readonly IRepository<ReservationStatus> _statusRepository;

       // [Authorize(Policy = PermissionTypeNames.ADMINISTRADOR)]
        public IActionResult Index()
        {
            List<Car> cars = (List<Car>) _carRepository.GetAll();
            return View(cars);
        }
       // [Authorize(Policy = PermissionTypeNames.ADMINISTRADOR)]
        public IActionResult Upsert(int? id)
        {
            CarViewModel model =
                new CarViewModel
                {
                    Car = new()
                };

            if (id == null || id == 0)
            {
                //insert car
                return View(model);
            }
            else
            {
                //update car
                model.Car = _carRepository.GetFirstOrDefault(x => x.Placa == id);
                return View(model);
            }
        }

        [HttpPost]
       // [Authorize(Policy = PermissionTypeNames.ADMINISTRADOR)]
        public IActionResult Upsert([FromForm]CarViewModel model)
        {
            if (ModelState.IsValid)
            {
                var noReserved = _statusRepository.GetFirstOrDefault(x => x.Id == 1);


                if (model.Car.Placa == 0)
                {
                    model.Car.Status = noReserved;
                    _carRepository.Add(model.Car);
                }
                else
                {
                    _carRepository.Update(model.Car);
                }
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(model);
        }

    }
}

LastTest.Responsive/Views/Shared/_CancelUpsertButtonsPartial.cshtml
@model string

<div class="form-group inputs">
         <a asp-controller="Administration" asp-action="Index" class="btn btn-danger" style="width:150px">
           Regresar a la lista </a>
    <button id="submit" type="submit" class="btn btn-outline-primary">
        <i class="fa-solid fa-floppy-disk"></i>
        @if (!string.IsNullOrEmpty(Model))
        {
            <span>Actualizar</span>
        }
        else
        {
            <span>Crear</span>
        }
    </button>
</div>

LastTest.Responsive/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Last Test</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <script src="https://kit.fontawesome.com/b4bbf55a6d.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Renta un Carro</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                         @if (User.IsInRole("Administrador"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Administration" asp-action="Index">Roles</a>
                                </li>
                                   <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Administration" asp-action="getAllUsers">Usuarios</a>
                                </li>
                                  <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Car" asp-action="Index">Carros</a>
                                </li>
                            }
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item text-right">
                                <a class="nav-link text-dark" asp-controller="Accounts" asp-action="Register">Registrar</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Accounts" asp-action="Login">Ingresar</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item text-right">
                                <form asp-controller="Accounts" asp-action="Logout" method="post">
                                    <button type="submit" class="nav-link text-dark btn border-0">
                                        Cerrar sesión
                                    </button>
                                </form>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - LastTest by Valeria Morales - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>